version: '1'
services:
  kadira:
    build: ./
    ports:
      - "11011:11011"
      - "8000:8000"
    environment:
      - APP_MONGO_URL=<APP_MONGO_URL>
      - APP_MONGO_OPLOG_URL=<APP_MONGO_OPLOG_URL>
      - DATA_MONGO_URL=<DATA_MONGO_URL>
      - AWS_ACCESS_KEY_ID=<AWS_ACCESS_KEY_ID>(optional)
      - AWS_SECRET_ACCESS_KEY=<AWS_SECRET_ACCESS_KEY>(optional)
      - AWS_BUCKET=<AWS_BUCKET>(optional)
      - AWS_DEFAULT_REGION=<AWS_DEFAULT_REGION>(optional)
